### ISSUE TITLE
Being able to specify the recordSchema with searchretrieve

### ISSUE THREAD

**Issue by edipretoro** [metaodi/sruthi#28]
When testing sruthi with <http://catalogue.bnf.fr/api/SRU>, I was not able to choose the format of the records returned by searchretrieve.

**Comment by metaodi** [comment]
Yes, this is actually a feature that I'm already working on, I try to push my PR for this soon.

**Comment by metaodi** [comment]
Fixed in release 0.1.1, see #30 for details.
